require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LabelDataSetsController do

  # This should return the minimal set of attributes required to create a valid
  # LabelDataSet. As you add validations to LabelDataSet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all label_data_sets as @label_data_sets" do
      label_data_set = LabelDataSet.create! valid_attributes
      get :index
      assigns(:label_data_sets).should eq([label_data_set])
    end
  end

  describe "GET show" do
    it "assigns the requested label_data_set as @label_data_set" do
      label_data_set = LabelDataSet.create! valid_attributes
      get :show, :id => label_data_set.id.to_s
      assigns(:label_data_set).should eq(label_data_set)
    end
  end

  describe "GET new" do
    it "assigns a new label_data_set as @label_data_set" do
      get :new
      assigns(:label_data_set).should be_a_new(LabelDataSet)
    end
  end

  describe "GET edit" do
    it "assigns the requested label_data_set as @label_data_set" do
      label_data_set = LabelDataSet.create! valid_attributes
      get :edit, :id => label_data_set.id.to_s
      assigns(:label_data_set).should eq(label_data_set)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LabelDataSet" do
        expect {
          post :create, :label_data_set => valid_attributes
        }.to change(LabelDataSet, :count).by(1)
      end

      it "assigns a newly created label_data_set as @label_data_set" do
        post :create, :label_data_set => valid_attributes
        assigns(:label_data_set).should be_a(LabelDataSet)
        assigns(:label_data_set).should be_persisted
      end

      it "redirects to the created label_data_set" do
        post :create, :label_data_set => valid_attributes
        response.should redirect_to(LabelDataSet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved label_data_set as @label_data_set" do
        # Trigger the behavior that occurs when invalid params are submitted
        LabelDataSet.any_instance.stub(:save).and_return(false)
        post :create, :label_data_set => {}
        assigns(:label_data_set).should be_a_new(LabelDataSet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LabelDataSet.any_instance.stub(:save).and_return(false)
        post :create, :label_data_set => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested label_data_set" do
        label_data_set = LabelDataSet.create! valid_attributes
        # Assuming there are no other label_data_sets in the database, this
        # specifies that the LabelDataSet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LabelDataSet.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => label_data_set.id, :label_data_set => {'these' => 'params'}
      end

      it "assigns the requested label_data_set as @label_data_set" do
        label_data_set = LabelDataSet.create! valid_attributes
        put :update, :id => label_data_set.id, :label_data_set => valid_attributes
        assigns(:label_data_set).should eq(label_data_set)
      end

      it "redirects to the label_data_set" do
        label_data_set = LabelDataSet.create! valid_attributes
        put :update, :id => label_data_set.id, :label_data_set => valid_attributes
        response.should redirect_to(label_data_set)
      end
    end

    describe "with invalid params" do
      it "assigns the label_data_set as @label_data_set" do
        label_data_set = LabelDataSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LabelDataSet.any_instance.stub(:save).and_return(false)
        put :update, :id => label_data_set.id.to_s, :label_data_set => {}
        assigns(:label_data_set).should eq(label_data_set)
      end

      it "re-renders the 'edit' template" do
        label_data_set = LabelDataSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LabelDataSet.any_instance.stub(:save).and_return(false)
        put :update, :id => label_data_set.id.to_s, :label_data_set => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested label_data_set" do
      label_data_set = LabelDataSet.create! valid_attributes
      expect {
        delete :destroy, :id => label_data_set.id.to_s
      }.to change(LabelDataSet, :count).by(-1)
    end

    it "redirects to the label_data_sets list" do
      label_data_set = LabelDataSet.create! valid_attributes
      delete :destroy, :id => label_data_set.id.to_s
      response.should redirect_to(label_data_sets_url)
    end
  end

end
