require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LabelDataController do

  # This should return the minimal set of attributes required to create a valid
  # LabelDatum. As you add validations to LabelDatum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all label_data as @label_data" do
      label_datum = LabelDatum.create! valid_attributes
      get :index
      assigns(:label_data).should eq([label_datum])
    end
  end

  describe "GET show" do
    it "assigns the requested label_datum as @label_datum" do
      label_datum = LabelDatum.create! valid_attributes
      get :show, :id => label_datum.id.to_s
      assigns(:label_datum).should eq(label_datum)
    end
  end

  describe "GET new" do
    it "assigns a new label_datum as @label_datum" do
      get :new
      assigns(:label_datum).should be_a_new(LabelDatum)
    end
  end

  describe "GET edit" do
    it "assigns the requested label_datum as @label_datum" do
      label_datum = LabelDatum.create! valid_attributes
      get :edit, :id => label_datum.id.to_s
      assigns(:label_datum).should eq(label_datum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LabelDatum" do
        expect {
          post :create, :label_datum => valid_attributes
        }.to change(LabelDatum, :count).by(1)
      end

      it "assigns a newly created label_datum as @label_datum" do
        post :create, :label_datum => valid_attributes
        assigns(:label_datum).should be_a(LabelDatum)
        assigns(:label_datum).should be_persisted
      end

      it "redirects to the created label_datum" do
        post :create, :label_datum => valid_attributes
        response.should redirect_to(LabelDatum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved label_datum as @label_datum" do
        # Trigger the behavior that occurs when invalid params are submitted
        LabelDatum.any_instance.stub(:save).and_return(false)
        post :create, :label_datum => {}
        assigns(:label_datum).should be_a_new(LabelDatum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LabelDatum.any_instance.stub(:save).and_return(false)
        post :create, :label_datum => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested label_datum" do
        label_datum = LabelDatum.create! valid_attributes
        # Assuming there are no other label_data in the database, this
        # specifies that the LabelDatum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LabelDatum.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => label_datum.id, :label_datum => {'these' => 'params'}
      end

      it "assigns the requested label_datum as @label_datum" do
        label_datum = LabelDatum.create! valid_attributes
        put :update, :id => label_datum.id, :label_datum => valid_attributes
        assigns(:label_datum).should eq(label_datum)
      end

      it "redirects to the label_datum" do
        label_datum = LabelDatum.create! valid_attributes
        put :update, :id => label_datum.id, :label_datum => valid_attributes
        response.should redirect_to(label_datum)
      end
    end

    describe "with invalid params" do
      it "assigns the label_datum as @label_datum" do
        label_datum = LabelDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LabelDatum.any_instance.stub(:save).and_return(false)
        put :update, :id => label_datum.id.to_s, :label_datum => {}
        assigns(:label_datum).should eq(label_datum)
      end

      it "re-renders the 'edit' template" do
        label_datum = LabelDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LabelDatum.any_instance.stub(:save).and_return(false)
        put :update, :id => label_datum.id.to_s, :label_datum => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested label_datum" do
      label_datum = LabelDatum.create! valid_attributes
      expect {
        delete :destroy, :id => label_datum.id.to_s
      }.to change(LabelDatum, :count).by(-1)
    end

    it "redirects to the label_data list" do
      label_datum = LabelDatum.create! valid_attributes
      delete :destroy, :id => label_datum.id.to_s
      response.should redirect_to(label_data_url)
    end
  end

end
